services:
  cosmic-ray-flux:
    image: cosmic-ray-fluxes:local
    build:
      context: ..
      dockerfile: run_using_docker/Dockerfile.technical
    restart: "no"
    read_only: true
    security_opt:
      - no-new-privileges:true
    command: ["31", "0.3", "15", "20", "-80", "2019", "5", "27", "0.15", "standard"]
